version: '3'
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    container_name: flask-app

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana